=== jimenj1970/shader-playground-site/Binaries/mali/7.3.0/samples/json_schemas/info-schema.json
{
    "$schema": "http://json-schema.org/schema#",

    "definitions": {
        "producer": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "array",
                    "minItems": 3,
                    "maxItems": 3,
                    "items": {
                        "type": "number"
                    }
                },
                "build": {
                    "type": "string"
                },
                "documentation": {
                    "type": "string"
                }
            },
            "required": ["name", "version", "build", "documentation"],
            "additionalProperties": false
        },
        "hardware": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string"
                },
                "core": {
                    "type": "string"
                },
                "revision": {
                    "type": "string"
                }
            },
            "required": ["architecture", "core", "revision"],
            "additionalProperties": false
        },
        "api": {
            "type": "object",
            "properties": {
                "max_version": {
                    "type": ["number", "null"]
                },
                "extensions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": ["max_version", "extensions"],
            "additionalProperties": false
        }
    },

    "type": "object",
    "properties": {
        "schema": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "const": "info"
                },
                "version": {
                    "type": "number",
                    "const": 0
                }
            },
            "required": ["name", "version"],
            "additionalProperties": false
        },
        "producer": {
            "$ref": "#/definitions/producer"
        },
        "hardware": {
            "$ref": "#/definitions/hardware"
        },
        "driver": {
            "type": "string"
        },
        "apis": {
            "type": "object",
            "properties": {
                "opengles": {
                    "$ref": "#/definitions/api"
                },
                "vulkan": {
                    "$ref": "#/definitions/api"
                },
                "opencl": {
                    "$ref": "#/definitions/api"
                }
            },
            "required": ["opengles", "vulkan", "opencl"],
            "additionalProperties": false
        }
    },
    "required": ["schema", "producer", "hardware", "driver", "apis"],
    "additionalProperties": false
}

=== jimenj1970/shader-playground-site/Binaries/mali/7.3.0/samples/json_reports/info-report.json
{
    "schema": {
        "name": "info",
        "version": 0
    },
    "producer": {
        "name": "Mali Offline Compiler",
        "version": [7, 2, 0],
        "build": "624fbd",
        "documentation": "https://developer.arm.com/mobile-studio/"
    },
    "hardware": {
        "architecture": "Valhall",
        "core": "Mali-G78",
        "revision": "r1p1"
    },
    "driver": "r25p0-00rel0",
    "apis": {
        "opengles": {
            "max_version": 320,
            "extensions": [
                "GL_ANDROID_extension_pack_es31a",
                "GL_ARM_shader_framebuffer_fetch",
                "GL_ARM_shader_framebuffer_fetch_depth_stencil",
                "GL_EXT_YUV_target",
                "GL_EXT_geometry_shader",
                "GL_EXT_gpu_shader5",
                "GL_EXT_primitive_bounding_box",
                "GL_EXT_shader_io_blocks",
                "GL_EXT_shader_non_constant_global_initializers",
                "GL_EXT_shader_pixel_local_storage",
                "GL_EXT_tessellation_shader",
                "GL_EXT_texture_buffer",
                "GL_EXT_texture_cube_map_array",
                "GL_KHR_blend_equation_advanced",
                "GL_OES_EGL_image_external",
                "GL_OES_EGL_image_external_essl3",
                "GL_OES_geometry_shader",
                "GL_OES_gpu_shader5",
                "GL_OES_primitive_bounding_box",
                "GL_OES_sample_variables",
                "GL_OES_shader_image_atomic",
                "GL_OES_shader_io_blocks",
                "GL_OES_shader_multisample_interpolation",
                "GL_OES_tessellation_shader",
                "GL_OES_texture_buffer",
                "GL_OES_texture_cube_map_array",
                "GL_OES_texture_storage_multisample_2d_array",
                "GL_OVR_multiview",
                "GL_OVR_multiview2"
            ]
        },
        "vulkan": {
            "max_version": 1.5,
            "extensions": [
                "SPV_EXT_descriptor_indexing",
                "SPV_EXT_fragment_invocation_density",
                "SPV_EXT_physical_storage_buffer",
                "SPV_EXT_shader_viewport_index_layer",
                "SPV_KHR_16bit_storage",
                "SPV_KHR_8bit_storage",
                "SPV_KHR_device_group",
                "SPV_KHR_float_controls",
                "SPV_KHR_multiview",
                "SPV_KHR_physical_storage_buffer",
                "SPV_KHR_shader_ballot",
                "SPV_KHR_shader_draw_parameters",
                "SPV_KHR_storage_buffer_storage_class",
                "SPV_KHR_subgroup_vote",
                "SPV_KHR_variable_pointers",
                "SPV_KHR_vulkan_memory_model"
            ]
        },
        "opencl": {
            "max_version": 200,
            "extensions": [
                "cl_arm_core_id",
                "cl_arm_printf",
                "cl_arm_thread_limit_hint",
                "cl_khr_3d_image_writes",
                "cl_khr_byte_addressable_store",
                "cl_khr_fp16",
                "cl_khr_global_int32_base_atomics",
                "cl_khr_global_int32_extended_atomics",
                "cl_khr_int64_base_atomics",
                "cl_khr_int64_extended_atomics",
                "cl_khr_local_int32_base_atomics",
                "cl_khr_local_int32_extended_atomics"
            ]
        }
    }
}
